### ISSUE TITLE
Cassandra - Add Cassandra Ingestion Tables

### ISSUE THREAD

**Issue by erikschlegel** [CatalystCode/project-fortis-spark#12]
Define table schemas in cassandra to support data ingestion for the following features.

- Topics
- Configuration Factories
- Aggregated Tiles
- Fortis Events
- Trusted profiles
- Facebook Pages 
- Site Configuration Settings

*What does complete mean*
Creating cassandra tables that support the features mentioned above. These tables should be created at site creation time as part of the deployment process.

**Comment by c-w** [comment]
This is implemented in [cassandra-setup.cql](https://github.com/CatalystCode/fortisdeploy/blob/56f9bc60d3b12d0699652ac4ad3f4785e00aa199/ops/storage-ddls/cassandra-setup.cql).

**Comment by c-w** [comment]
Resolving this this had already been implemented a while ago.
