### ISSUE TITLE
Spark Pipeline - Aggregate pipeline data into geotiles in Cassandra

### ISSUE THREAD

**Issue by erikschlegel** [CatalystCode/project-fortis-spark#13]
Transform the filtered normalized results from the streaming connector pipeline and aggregate into the tiles cassandra table which follows the attached schema. 

*What does complete mean*
Results are aggregated by the composite key as outlined in the attachment and written to cassandra. This also involves 

![tile_schema](https://user-images.githubusercontent.com/7635865/27196652-f732a944-51d0-11e7-8e19-9df9314414e0.png)

**Comment by c-w** [comment]
See [CassandraEventsSink](https://github.com/CatalystCode/project-fortis/blob/cfe7afb4978e256baff0484fd1d0584a676b00e7/project-fortis-spark/src/main/scala/com/microsoft/partnercatalyst/fortis/spark/sinks/cassandra/CassandraEventsSink.scala).

Resolving this this had already been implemented a while ago.
