### ISSUE TITLE
Dashboard - Refactor GraphQL Services to support cassandra schema

### ISSUE THREAD

**Issue by erikschlegel** [CatalystCode/project-fortis-spark#16]
The GraphQL schema and resolvers will need to be refactored to support reading / writing it's data from Cassandra. Currently, our graphql servers read / write data from azure table storage and postgres. This needs to be refactored to read / write from only cassandra. Postgres will only be used for news feed queries to collect the feature ids that intersect with the users current map bounds from the heatmap. 

We should reorganize the existing schema to consolidate the flow-based type definitions.

*What complete means*
Here's a listing of the schemas that will need to be refactored
- Edges Schema(used for terms and locations) - This will also need to support both entities, data source and source publisher. 
- Messages Schema
- Facts Schema should be consolidated into the Messages Schema
- Settings Schema
- Tiles Schema 
- Aggregated Edges - popular locations, popular terms, etc

A listing of the refactored resolvers that will need to be adjusted
- Edges: terms, locations, removeKeywords, addKeywords, saveLocations, removeLocations, popularLocations, timeSeries and topSources
- Facts(should be consolidated into Messages): list & get
- Messages: byBbox, byLocation, byEdges, eventDetails, publishEvents, translate and translateWords
- Settings(ie the admin interface services): sites, createOrReplaceSite, modifyFacebookPages, modifyTrustedTwitterAccounts, removeFacebookPages, removeTrustedTwitterAccounts, modifyTwitterAccounts, removeTwitterAccounts, twitterAccounts, trustedTwitterAccounts, facebookPages, facebookAnalytics, termBlacklist, modifyBlacklist, removeBlacklist
- Tiles: fetchTilesByBBox, fetchTilesByLocations, fetchPlacesByBBox, fetchEdgesByLocations and fetchEdgesByBBox

**Comment by c-w** [comment]
This task should be implemented after #17 -- in #17 we're going to re-implement all the existing resolvers in function of the new Cassandra data schema. After that is done, we can add new functionality as described in this task.
