### ISSUE TITLE
Spark Documentation

### ISSUE THREAD

**Issue by erikschlegel** [CatalystCode/project-fortis-spark#165]
We need to give some much needed TLC to this repos README . The readme should provide clear guidance for new Fortis developers. 

**Documentation should cover the following criteria**

- [ ] 1. Install Spark on a local machine. This should include instructions on where to go for the install and what version a dev should use
- [ ] 2. all the necessary steps for setting up the project. This should mention that we're dependent on IntelliJ(specify versions and download locations). This should also mention what repo to clone, how to create a new project in Intelli, and what project file to link to. What version of SBT and Scala that needs to be installed.
- [ ] Please include as much screen shots as necessary
- [ ] 3. Steps for installing cassandra locally. This should also include steps for starting cassandra
- [ ] 4. Steps for setting up all the cassandra objects on their local instance
- [ ] 5. Steps for testing the Cassandra Spark aggregation push
- [ ] 6. Steps for running / debugging the pipeline on IntelliJ
- [ ] 7. Steps for running all the unit tests (edited)
- [ ] 8. Steps for setting up the kube proxy to monitor the spark job. This should entail URL links, etc
- [ ] 9. Steps for pushing new changes to the pipeline(increment sbt version, cut a new release in GH, links to the travis build, instructions on force starting the build, etc).
- [x] 10. Deployment of new release to Kubernetes pod.
- [x] 11. Environment variables that need to be set. We should also have sample site config and trustedsource record insert statements that we can refer developers to.

**Comment by c-w** [comment]
This is now all codified via the [Dockerfile](https://github.com/CatalystCode/project-fortis/blob/cfe7afb4978e256baff0484fd1d0584a676b00e7/project-fortis-spark/docker/Dockerfile).
