### ISSUE TITLE
Filter retweets

### ISSUE THREAD

**Issue by erikschlegel** [CatalystCode/project-fortis-spark#172]
We should remove any events marked as a retweet through the Twitter Analyzer

Currently, we're processing messages marked as retweets, which is making up a large number of the Fortis events. This creates duplicative events, and floods our spark streaming job with a high volume of content. 

We should enhance the Twitter Streaming Factory and filter out retweets, similar to the exiting profile filter that's in place.

**Comment by c-w** [comment]
Looks like this is now happening in [TwitterStreamFactory](https://github.com/CatalystCode/project-fortis/blob/cfe7afb4978e256baff0484fd1d0584a676b00e7/project-fortis-spark/src/main/scala/com/microsoft/partnercatalyst/fortis/spark/sources/streamfactories/TwitterStreamFactory.scala#L68-L83)
