### ISSUE TITLE
GraphQL- Add Crisis Lex integration 

### ISSUE THREAD

**Issue by erikschlegel** [CatalystCode/project-fortis-spark#18]
Integrate the Crisis lex lexicon category list to fortis as the default topic list that's setup when a site is first deployed.

The source lexicon list should be sourced from the data directory of the crisis lex GH repo https://github.com/sajao/CrisisLex/tree/master/data .

*What complete means*
- Normalize all the datasets available from lexicon repo into a unique, consolidated and conditioned dataset available on our blob storage container which is currently hosting our sentiment models. 
- This should be organized in a directory structure following the convention `/fortis/{type}/defaultTopics/`
- modify the `createOrReplaceSite` graphql endpoint to accept the `siteType` input parameter and reference all topics for the input `{type}` from blob storage. 
- Push one record in the `Topics` table in Cassandra for each topic sourced from our blob storage container.

**Comment by Smarker** [comment]
![diagram](https://user-images.githubusercontent.com/7232635/27239774-48541536-52a0-11e7-985d-9fab6c67fe49.png)
Diagram Clemens made during our conversation about how the fortis pipeline is set up.
