### ISSUE TITLE
Add pipeline for custom events

### ISSUE THREAD

**Issue by c-w** [CatalystCode/project-fortis-spark#30]
Fortis-v1 has a feature where users can upload custom events and have them analyzed via the Fortis pipeline. See [publishEvents](https://github.com/CatalystCode/project-fortis-services/blob/1c2e6ad6939d0c3e5eed2e6e9622460ae714103c/src/schemas/MessageSchema.js#L19-L46) for reference.

If we want to support this feature in Fortis-v2, we need to add a [pipeline](https://github.com/CatalystCode/project-fortis-spark/tree/257576dcaa2b72a13109c30c3edb5cb0986a139c/src/main/scala/com/microsoft/partnercatalyst/fortis/spark/pipeline) via which to ingest these custom events.

One possible implementation of this is to use [EventHub](https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-what-is-event-hubs) with the Spark pipeline acting as a consumer and the resolver that implements publishEvents acting as a producer.

We already have code to interface with EventHub from Spark ([EventHubStreamFactory](https://github.com/CatalystCode/project-fortis-spark/blob/257576dcaa2b72a13109c30c3edb5cb0986a139c/src/main/scala/com/microsoft/partnercatalyst/fortis/spark/streamfactories/EventHubStreamFactory.scala#L13)) so it shouldn't take more than 1-1.5 days to build all the required pieces:

(1) Define the schema for the custom events
(2) Define a name for the custom events EventHub
(3) Add a new pipeline that processes events from EventHub
(4) Set up a dummy EventHub in our Azure subscription for testing

**Comment by c-w** [comment]
Adding @erikschlegel to give thumbs-up/down on whether we want to implement this.

**Comment by erikschlegel** [comment]
Your assumption is spot on. For custom events today, we push those messages into event hub which leverages the same flow as tadaweb. 👍

**Comment by kevinhartman** [comment]
Fitting into step (3) above, `StreamProvider` was designed with this in mind :) Just need to add a model and adapter for custom events and then attach another EH stream factory to our provider instance to add support:
```scala
.withFactories(
  List(
    new EventHubStreamFactory("CustomEvent", CustomEventAdapter.apply,
      settings.progressDir)
  )
)
```

We'll define a CustomEvent pipeline as mentioned in (3) as well.

**Comment by c-w** [comment]
I can take this one tomorrow morning.

**Comment by c-w** [comment]
Branch for putting custom events onto the EventHub: [publish-events-resolver](https://github.com/CatalystCode/project-fortis-services/tree/publish-events-resolver).

**Comment by c-w** [comment]
Branch for consuming the custom events from the EventHub: [customevents](https://github.com/CatalystCode/project-fortis-spark/tree/customevents).
