### ISSUE TITLE
Duplicates in keyword extraction

### ISSUE THREAD

**Issue by erikschlegel** [CatalystCode/project-fortis-spark#4]
If a keyword/phrase appears multiple times in the event text, the the list of extracted keywords will contain an entry of the keyword/phrase for each occurrence. An AnalyzedItem's tags field (along with several other collection-typed fields) should be a Set. Once that's done, the keyword extractor's interface should be made to work with Sets instead of Lists.

**Comment by c-w** [comment]
We're already discarding the repeated events when we're publishing the events to Cassandra ([see the schema](https://github.com/CatalystCode/project-fortis-spark/blob/8cddda4731e5157691d0008b46426dc68ebc00ee/src/main/scala/com/microsoft/partnercatalyst/fortis/spark/sinks/cassandra/CassandraSchema.scala#L31-L44)) so the duplicates shouldn't have an impact.

As such, we can keep around the duplicates until publishing time in case we want to do something with the duplicate information. E.g. we may want to treat an event that mentions "ISIS" multiple times differently from one that mentions "ISIS" just once for some analyses. Additionally, having the raw occurrence count information as opposed to just a binary occurrence indicator will be useful for some of the machine learning models that we may want to build on top of the events data.
