### ISSUE TITLE
Fix K8 spark-submission job issue

### ISSUE THREAD

**Issue by erikschlegel** [CatalystCode/project-fortis-spark#50]
Fix spark submission job issue when the spark master pod is deployed on the fortis spark cluster.

**Comment by kevinhartman** [comment]
The value of environment variable`SPARK_MASTER_PORT=tcp://10.0.155.102:7077` should just be the port `7077`. For this reason, the spark master process was not coming up, and hence was unavailable during job submission.

This is also likely true for `tcp://10.0.191.165:8080`, though that's a separate issue.

**Comment by kevinhartman** [comment]
This was due to the spark submission command overriding the command that starts the Spark master in a vanilla Spark deployment.

Resolved by
https://github.com/CatalystCode/project-fortis-pipeline/pull/88
https://github.com/CatalystCode/charts/pull/19
