### ISSUE TITLE
Spark Pipeline - Add AppInsights

### ISSUE THREAD

**Issue by Smarker** [CatalystCode/project-fortis-spark#62]
**Goal:** Add appinsights to increase visibility within the spark pipeline.

_What does complete mean:_
* Add event tracking with properties and metrics
* Log fatal exceptions
* Add appinsights webhooks to provide Slack notifications on fatal exceptions.

**Comment by Smarker** [comment]
Pending work:

- decide on a better name for a "batch of events" event than the current name, `process.events`
- add more telemetry around specific slices of the pipeline such as the `analysis stage` as well as `saving to cassandra`
- add `slack notifications` on fatal exceptions

**Comment by c-w** [comment]
Lots more logging now added in [project-fortis](https://github.com/CatalystCode/project-fortis):

![image](https://user-images.githubusercontent.com/1086421/35007837-ab84f212-fac8-11e7-9b50-c9605950529c.png)

![image](https://user-images.githubusercontent.com/1086421/35007858-bb8f1aa2-fac8-11e7-9b3a-9121b3bc7cf2.png)
